### PR TITLE
Upgrade version 1.0-edr1 to 1.0-edr2 .

### PR DESCRIPTION
**Pull request by Daniel-Dos**
I upgraded the Early Draft Release version to the current version of the API.

regards,
Daniel Dias

### CODE REVIEW

**Comment by chkal** [comment]
Thanks a lot! The first version of the index page was a copy from the old web site which wasn't updated for a while!

**Comment by Daniel-Dos** [comment]
True, I had seen it for a while, but I did not know where the page was for change. Now with this new version it is easier to control the possible changes.

Thank you very much for accepting the PR.

{ },s.

**Comment by chkal** [comment]
That's great! I also informed the former spec leads about this some time ago, but they didn't update it.

I'm curious. How did you find this repo and the new page? I created it yesterday and you provided a PR a few hours later.

**Comment by Daniel-Dos** [comment]
This happened last year at a meeting of SouJava, where we are discussing some JSR's. However no one in the group was following the process, it was then that I begged if I wanted to follow their evolution and participate in the lists of speech.

From there I went to look for some subjects and examples of its use. Until arriving at the page of the JIRA that is in the main page https://jcp.org/en/jsr/detail?id=371 where I had a link to Issue Tracking and from there I went looking at the activities, there I found a link for PR that I Led to the repository.

**Comment by chkal** [comment]
Ah, OK! Great! Thanks for the PR.

**Comment by Daniel-Dos** [comment]
I thank you and sorry for anything

{ },s.

**Pull request merged**
