### PR TITLE
Update to latest snapshot of spec pdf

### PR DESCRIPTION
**Pull request by ivargrimstad**

### CODE REVIEW

**Comment by chkal** [comment]
Hey @ivargrimstad. Looks like the URL contains the exact timestamp of the snapshot. So I guess we are linking to a very specific snapshot version which won't update to the latest one.

I tried to find out how to link to the latest snapshots, but it doesn't seem to be easy. The only reference I found was this part of the REST API:

https://repository.sonatype.org/nexus-restlet1x-plugin/default/docs/path__artifact_maven_redirect.html

Got it from this old SO post:

https://stackoverflow.com/a/9284542/395181

But it doesn't seem to work for some reason... :cry:

**Comment by ivargrimstad** [comment]
I'll update it

**Comment by chkal** [comment]
Awesome! Thanks...

**Comment by chkal** [comment]
My attempts were failing for 20 minutes as I was using `repository.sonatype.org` instead of `oss.sonatype.org` :laughing:

**Pull request merged**
