### PR TITLE
Install guide for Wildfly and Glassfish

### PR DESCRIPTION
**Pull request by gtudan**
I documented and tested the installation on wildfly 10/wildfly swarm and Glassfish/Payara. TomEE didn't work out of the box and I didn't want to go into the details of replacing cxf with jersey, as this would missing the point of an application server. I'll file an issue for CXF-support and look into it, shouldn't be to hard.

### CODE REVIEW

**Comment by chkal** [comment]
That's awesome! Thanks a lot.

Regarding CXF: Have a loot at mvc-spec/ozark#131. The compatibility issues with CXF are discussed here and there is already an CXF bug report in their issue tracker.

**Comment by chkal** [comment]
I think we should keep it for now. I'm not yet 100% sure that all the Ozark features work with RESTEasy. And the test coverage for Jersey is much better.

**Comment by gtudan** [comment]
+1 for removing it. I tried running Jersey on wildfly and got into loads of trouble with it. It conflicts with just about anything that has something to do with servlets and you end up configuring servlet handlers in the web.xml.

People knowing what they do will figure out how to use Jersey themselfs and the rest shouldn't go down this road.

**Comment by chkal** [comment]
@gtudan Could you share your opinion about how good Ozark works on plain Wildfly with RESTEasy? I didn't find much time to have a deeper look at it beyond simple tests.

**Comment by gtudan** [comment]
Quiet good actually. I tested the basics with the jsp-Engine, Form- and Beanbinding, Validation and exception-handling and redirects (without the CDI redirect-scope). All of those worked flawless and out of the box with the latest snapshot.

I haven't tried CSRF, the MVC-Context, internationalization and events yet.

**Comment by chkal** [comment]
Nice! Thanks a lot for sharing your experiences...

In this case we may really remove the Wildfly+Jersey guide. Especially as we now have a nice guide covering the setup in popular app servers.

**Pull request merged**
