### PR TITLE
Tomcat/TomEE guide

### PR DESCRIPTION
**Pull request by Daniel-Dos**
adding guide to using Ozark in tomcat / tomee with the ozark-resteasy module.

tested with:
- apache-tomee-plus-7.0.4
- apache-tomcat-8.5.24

### CODE REVIEW

**Comment by chkal** [comment]
Awesome! Thanks a lot! I'll merge this immediately. 

We may need to restructure the docs a bit after we got all the configurations documented. But we can do this later.

**Comment by Daniel-Dos** [comment]
thank you so much.

By the way, when I access the new pages I'm getting this:

`Internal Server Error - REquest ID: a9f07344-69c8-418c-9094-07009b6c25c3-53950529`

**Comment by chkal** [comment]
Hmmm. I'm also getting this error. I just restarted the build job. Let's see if this helps.

**Comment by chkal** [comment]
Looks like a redeployment of the site fixed the problem.

**Pull request merged**
