### PR TITLE
Add metadata-complete="true" to sample web.xml

### PR DESCRIPTION
**Pull request by mthmulders**
Follow-up on eclipse-ee4j/krazo#80, this updates the docs accordingly.

### CODE REVIEW

**Comment by chkal** [comment]
Thanks for this update. But to be honest, I'm not sure if we should recommend this approach, because it will most likely cause other issues, because the auto discovery will stop to work as expected. Let's wait a bit to see what the RESTEasy team thinks about my comment.

**Comment by chkal** [comment]
I'm still thinking that this is a RESTEasy bug and trying to kickstart some discussion in the corresponding [upstream issue](https://issues.jboss.org/browse/RESTEASY-2289).

**Comment by mthmulders** [comment]
Sure, let's await that discussion first.

**Comment by mthmulders** [comment]
I've been following the discussion in [RESTEASY-2289](https://issues.jboss.org/browse/RESTEASY-2289). The last remark from the RESTEasy team was

> The resteasy team will continue evaluating how this issue can better be addressed going forward.

And in the same message they also stated that 

> an alternative is to use the metadata-complete="true" attribute and fully define the application in the web.xml file

So maybe we should update the Krazo docs to at least mention this as a "temporary" work-around for the fact that RESTEasy (and thus Krazo) will either start twice or not at all?

**Comment by chkal** [comment]
> So maybe we should update the Krazo docs to at least mention this as a "temporary" work-around for the fact that RESTEasy (and thus Krazo) will either start twice or not at all?

Yeah, sounds good. I just want to make sure we don't recommend it for everyone, because it definitely has side effects for other frameworks and libraries.

**Comment by chkal** [comment]
Thanks a lot! :+1: :beers:

**Pull request merged**
